name: arcane_fcm
description: "FCM Messaging in Arcane"
version: 1.0.0
repository: https://github.com/ArcaneArts/arcane_fcm
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  arcane: ">=5.3.3 <6.0.0"
  serviced: ">=1.0.3 <2.0.0"
  flutter_local_notifications: ">=19.0.0 <20.0.0"
  device_info_plus: ">=11.3.3 <12.0.0"
  firebase_messaging: ">=15.2.5 <16.0.0"
  arcane_auth: ">=1.7.1 <2.0.0"
  crypto: ">=3.0.6 <4.0.0"
  fast_log: ">=1.0.7"
  arcane_fcm_models: ">=1.1.0 <2.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter: